spring:
  application:
    name: wechat-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true #注册自身
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  datacenter: cloud
  environment: product

# 公众号配置 改成你的配置
wx:
  mp:
    appid: xxxx
    secret: xxxx
    token: yunzhi
    aesKey: 123

